### ISSUE TITLE
Oh Noes! 500

### ISSUE THREAD

**Issue by zephyrweb** [NancyFx/Nancy.Blog#19]
http://blog.nancyfx.org/

```
Nancy.RequestExecutionException: Oh noes! ---> System.Xml.XmlException: The element with name 'html' and namespace '' is not an allowed feed format.
   at System.ServiceModel.Syndication.SyndicationFeed.Load[TSyndicationFeed](XmlReader reader)
   at Nancy.Blog.Services.CachedFeedService.GetFeed(String url, String id, List`1 syndicationFeeds)
   at Nancy.Blog.Services.CachedFeedService.GetSyndicationFeeds(IEnumerable`1 metadataEntries)
   at Nancy.Blog.Services.CachedFeedService.GetItemsForCache(Int32 feedCount, Int32 pagenum)
   at Nancy.Blog.Services.CachedFeedService.GetItems(Int32 feedCount, Int32 pagenum)
   at Nancy.Blog.Services.PostService.GetViewModel(Int32 feedCount, Int32 pagenum)
   at Nancy.Blog.Modules.HomeModule.<>c__DisplayClass1a.<.ctor>b__12(Object _)
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.b__3(Object parameters, CancellationToken context)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

**Comment by phillip-haydon** [comment]
Thanks @zephyrweb it's fixed now.
